---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:235494798709:task-definition/Spring-task:3"
        LoadBalancerInfo:
          ContainerName: "karthik-z"
          ContainerPort: 8080
