version: 0.2
 
phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - yum install -y jq maven
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=423623849965
      - REGION=us-east-1
      - REPO_NAME=spring
      - IMAGE_TAG=latest
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
 
  build:
    commands:
      - echo Building the JAR file...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $ECR_URI:$IMAGE_TAG .
 
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $ECR_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"bhargav","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $ACCOUNT_ID $REGION $REPO_NAME $IMAGE_TAG > imagedefinitions.json
      - echo Writing appspec.yml...
 
artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
